#!/bin/bash
#SBATCH --job-name=QASRTTS             # Job name
#SBATCH --output=./_logs/QASRTTS_v1.%A_%a.txt   # Standard output and error log
#SBATCH --nodes=1                   # Run all processes on a single node    
#SBATCH --ntasks=1                  # Run on a single CPU
#SBATCH --mem=128G                   # Total RAM to be used
#SBATCH --cpus-per-task=8          # Number of CPU cores
#SBATCH --gres=gpu:1              # Number of GPUs (per node)
#SBATCH -p gpu                      # Use the gpu partition
#SBATCH --time=12:00:00             # Specify the time needed for your experiment
#SBATCH -q gpu-8                    # To enable the use of up to 8 GPUs


hostname
bash -l finetune.sh